---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vokmon/spring-cloud
          #username: uname
          #password: pass
          
          # primary repo
          search-paths:
            - 'spring-cloudconfig-wa-tolls/station*' 
            #localhost:8888/s1rates/master
            #localhost:8888/s1rates/dev
            #localhost:8888/s2rates/master
            #localhost:8888/s2rates-default.properties /  localhost:8888/s2rates-default.yml
            #localhost:8888/s1rates-dev.json / localhost:8888/s2rates-default.json /
          # secondary repo
          repos:
            perf:
              pattern:
                -*/perf
              # does not work
              uri: https://github.com/vokmon/spring-cloud/tree/master/spring-cloudconfig-wa-tolls-perf
              search-paths:
                - 'station*'